#!/bin/bash
#SBATCH -N 430
#SBATCH -q low
#SBATCH -t 00:20:00
##SBATCH --time-min 00:20:00
#SBATCH -A m499
#SBATCH -L SCRATCH
#SBATCH -C knl,quad,cache
#SBATCH -S 4
##SBATCH --mail-type=BEGIN,END,FAIL
##SBATCH --mail-user=jdominsk@pppl.gov
#SBATCH --job-name=wdmapp

./runscript

